### ISSUE TITLE
Issue when building with indicators

### ISSUE THREAD

**Issue by Brucuz** [magr0s/vue-scrollmagic#1]
I've tried using the configuration in vue.config.js and then importing the indicators in main.js.
It works fine during development but i breaks with npm run build because it does not find the plugin in main.js. I can try some workaround but i was wondering if there is any "clean" fix.
PS: anyway thanks for this repository it is really helpful

**Comment by magr0s** [comment]
Hi!
Show me your webpack.config.js or vue.config.js

Thanks
