### ISSUE TITLE
destroy method

### ISSUE THREAD

**Issue by regenrek** [magr0s/vue-scrollmagic#10]
Hi,

if I destroy the controller in my `destroyed()` method, there doesn't
seem to be a possibility to reinit the scrollmagic instance.

```
        destroy (resetScenes = false) {
          return this.controller_.destroy(resetScenes)
        },
```

**Comment by magr0s** [comment]
Hi.

Yes, according to the [ScrollMagic documentation](http://scrollmagic.io/docs/ScrollMagic.Controller.html#destroy), this method destroys everything.
So use it with caution.

This method will be advantageous for temporary controllers.
